### ISSUE TITLE
[Bug] Notifications about boosts are not deleted

### ISSUE THREAD

**Issue by tcely** [zactopus/please-caption-mastodon#8]
Adding support for boosts #5 has left me with a reply to a post that's direct to my account, but that isn't deleted when I favorite it. This is because I wasn't the author of the post that I boosted.

https://github.com/zactopus/please-caption-mastodon/blob/f57dc39b204166be42cf7d7c0e91567517b98c32/js/bot.js#L147

**Comment by zactopus** [comment]
Thanks for the bug report

**Comment by zactopus** [comment]
Looking into this I think we can either:

1. Check to see if the username is in the toot
2. Not check at all because we can assume only one person recieves the toot as it's a direct message

I think let's do 2 because we've got bigger problems if bot messages are being sent to the wrong people
